apiVersion: v1
kind: Service
metadata:
  name: hello-web-svc
  labels:
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/part-of: hello-k8s
spec:
  type: NodePort
  selector:
    app: hello-web      # matcher deploymentens selector
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
